# Config file for travis-ci.org

name: PHP Tests and Code Style

on: [push]

jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: 7.3 # 7.4 not yet working correctly

      - name: retrieve script
        run: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

      - name: Install DokuWiki
        env:
          CI_SERVER: 1
          DOKUWIKI : master
        run: sh travis.sh

      - name: Download PHPCS
        run: wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

      - name: run PHP codesniffer
        run: php phpcs.phar -v --standard=_test/phpcs.xml lib/plugins/personaltodo
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        operating-system: [ ubuntu-18.04 ]
        php: [
            '7.2',
            '7.3',
            # '7.4', not yet working correctly
        ]
    name: PHP ${{ matrix.php }} sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: retrieve script
        run: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

      - name: Install DokuWiki
        env:
          CI_SERVER: 1
          DOKUWIKI : master
        run: sh travis.sh

      - name: Run tests
        run: cd _test && ./phpunit.phar --stderr --group plugin_personaltodo
