# Config file for travis-ci.org

name: PHP Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        operating-system: [ ubuntu-18.04 ]
        php: [
            '7.2',
            '7.3',
            # '7.4', not yet working correctly
        ]
    name: PHP ${{ matrix.php }} sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: retrieve script
        run: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

      - name: Install DokuWiki
        env:
          CI_SERVER: 1
          DOKUWIKI : master
        run: sh travis.sh

      - name: Run tests
        run: cd _test && ./phpunit.phar --stderr --group plugin_personaltodo
